package com.example.prygoon.testmap.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.prygoon.testmap.model.User;
import com.example.prygoon.testmap.model.Coordinates;

import com.example.prygoon.testmap.model.UserDao;
import com.example.prygoon.testmap.model.CoordinatesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig coordinatesDaoConfig;

    private final UserDao userDao;
    private final CoordinatesDao coordinatesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        coordinatesDaoConfig = daoConfigMap.get(CoordinatesDao.class).clone();
        coordinatesDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        coordinatesDao = new CoordinatesDao(coordinatesDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Coordinates.class, coordinatesDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        coordinatesDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public CoordinatesDao getCoordinatesDao() {
        return coordinatesDao;
    }

}
